### ISSUE TITLE
the problems when run ast_models.py 

### ISSUE THREAD

**Issue by ctwgL** [YuanGongND/ast#1]
Hello, when I run the ast_models.py,  the folowing problem occured. 
![image](https://user-images.githubusercontent.com/38711953/126174877-6f4958b6-8c48-4a69-85a1-f711e4dd5bcf.png)

**Comment by YuanGongND** [comment]
Hi there,

I just ran the ast_models.py in my environment but could not reproduce it. Could you please elaborate on how you ran the code (i.e., directly run ast_models.py or call it from another script? Have you changed anything of ast_models.py)? Thanks!

Yuan

**Comment by ctwgL** [comment]
I just directly run the ast_models.py, Because I just want to test the pretrained AudioSet model, so I delete the code when   audioset_pretrain == False.  I will test it again tomarrow.

**Comment by YuanGongND** [comment]
Oh, you should not delete the code when audioset_pretrain==False, because when you set audioset_pretrain==True, it will initialize an AST model without pretraining and then load the weights. So please keep the ASTModel class unchanged and test again. Let me know if the problem is still there.

-Yuan
