### ISSUE TITLE
Parameters for tuning

### ISSUE THREAD

**Issue by lyghter** [YuanGongND/ast#33]
Hello @YuanGongND. I am trying to train AST on a dataset, which is very similar to Speech Commands, but:
- max lenght of WAVs is 64000 frames (vs 16000 in SC)
- test part contains very noisy samples

1. Could you advise me, which params should I change? 
2. I have enough resources and I want to increase the accuracy. How can I do this?

**Comment by lyghter** [comment]
Thanks. Could you give me a hint on how hyperparameters (freqm, timem and num_mel_bins) might affect on model accuracy and memory usage? Should num_mel_bins be equal to input_tdim?

**Comment by lyghter** [comment]
My dataset: 
64000 samples -> target_length=640
Speech commands: 
16000 samples -> target_length=128 (why not 160?)

**Comment by YuanGongND** [comment]
Sorry, I am wrong, 64000 samples should be 64000/16000/0.01=400 frames if your sampling rate is 16kHz. ``freqm`` and ``timem`` has a relatively small impact on the performance, ``fstride`` and ``tstride`` do not depend on input audio length, so you can reuse our parameters. ``num_mel_bins`` and ``input_tdim`` are completely different and should not be the same, the first is the number of frequency bins of the spectrogram, the second is the frame number. They are the same for SC dataset because of coincidence. 

``target_length=100`` should be sufficient for SC dataset, but we just use 128 to guarantee all audios are shorter than the ``target_length``.

Best,
Yuan
